name: Build

on:
  push

jobs:
  Windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Get commit hash
      run: |
        'CommitHash=$(git rev-parse --short=7 HEAD)' >> $env:GITHUB_ENV

    - name: Get current date
      run: |
        echo "CurrentDate=$(date +'%Y-%m-%d')" >> $env:GITHUB_ENV

    - name: Pull dependencies
      run: ${{github.workspace}}\build-initdeps.bat

    - name: Compile binaries
      run: ${{github.workspace}}\build-MetaAudio.bat

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: '${{env.CurrentDate}}_MetaAudio-${{env.CommitHash}}'
        path: '${{github.workspace}}/build/externals'

    - name: Compress artifacts
      uses: papeloto/action-zip@v1
      with:
        files: '${{github.workspace}}/build/externals/'
        dest: '${{github.workspace}}/${{env.CurrentDate}}_MetaAudio-${{env.CommitHash}}.zip'

    - name: GitHub pre-release
      uses: 'marvinpinto/action-automatic-releases@latest'
      with:
        repo_token: '${{secrets.GITHUB_TOKEN}}'
        automatic_release_tag: 'latest'
        prerelease: true
        title: '[${{env.CurrentDate}}] MetaAudio-${{env.CommitHash}}'
        files: '${{env.CurrentDate}}_MetaAudio-${{env.CommitHash}}.zip'
