name: Build

on:
  push

jobs:
  Windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    
    - name: Pull dependencies
      run: |
        ${GITHUB_WORKSPACE}\build-initdeps.bat

    - name: Compile binaries
      run: |
        ${GITHUB_WORKSPACE}\build-MetaAudio.bat
