name: Build

on:
  push

jobs:
  Windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    
    - name: Pull dependencies
      run: |
        echo cd
        echo %cd%
        build-initdeps.bat

    - name: Compile binaries
      run: |
        echo cd
        echo %cd%
        build-MetaAudio.bat
