name: Build

on:
  push

jobs:
  Windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    
    - name: Pull dependencies
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: build-initdeps.bat

    - name: Compile binaries
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: build-MetaAudio.bat
