name: Build

on:
  push

jobs:
  Windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    
    - name: Pull dependencies
      run: ${{github.workspace}}\build-initdeps.bat

    - name: Compile binaries
      run: ${{github.workspace}}\build-MetaAudio.bat

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: MetaAudio
        path: ${{github.workspace}}\build
