name: Build

on:
  push

jobs:
  Windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: build-initdeps.bat

    - name: make
      run: build-MetaAudio.bat
